#! /bin/bash

echo "Scanning for transactions associated with this wallet..."; while [ $(space-cli getwalletinfo | jq '.tip') -lt $(space-cli getserverinfo | jq '.tip.height') ]; do echo -n "Scanning: "; echo -n $(space-cli getwalletinfo | jq '.tip'); echo " of " $(space-cli getserverinfo | jq '.tip.height') " blocks"; sleep 2; done ; echo "Finished Scanning"